%% main_gui(action,varargin)
%% mida group http://mida.dima.unige.it  2010 - 2015
%%%% this function calls the gui for the software where one can load the
%%%% data, create the roi, set the desired output and run the code

%%%% call: Load_Data();
%%%%       Slider_Contrast(); Slider_WindowsUp(); Slider_WindowsDown();
%%%%            Slider_Image;
%%%%       PopUp_Districts;
%%%%       Roi_Rectangle; Roi_Ellipse; Roi_End;
%%%%       Enable_Roi; Enable_Txt; Enable_Dicom;
%%%%       Reset_Roi; Reset_All; Save_All;
%%%%       Start_Analysis
function main_gui(action,varargin)

if nargin<1,
    
    action='gui';
    
end
feval(action,varargin{:});
end
%% ************************************************************************
%% ************************************************************************
function gui()
clear global;

global pet_gui;
global pos;

if ispc==1, pet_gui.slash_pc_mac='\'; else pet_gui.slash_pc_mac='/'; end

screen_x=.8;
screen_y=.8;
scrsz = get(0,'ScreenSize');

%%%% gui position
position(1,3)=round(scrsz(1,3)*screen_x); %-x
position(1,4)=round(scrsz(1,4)*screen_y); %-y
position(1,1)=round((scrsz(1,3)*.99-position(1,3)));
position(1,2)=round((scrsz(1,4)-position(1,4))/2);

%%%% scale factor for gui
vect_pixel_sambu=[1920 1058 1920 1058];
vect_pixel_screen=[scrsz(1,3),scrsz(1,4),scrsz(1,3),scrsz(1,4)];
scale_factor=(vect_pixel_screen./vect_pixel_sambu).*[screen_x/.6 screen_y/.7 screen_x/.6 screen_y/.7];


pos.FIGURE=position;
%%%% PANEL LOAD - position
pos.PANELload.panel=round([15,680,1122,60].*scale_factor);
pos.PANELload.PBload=round([15,5,120,25].*scale_factor);
pos.PANELload.TXTload=round([150,5,957,25].*scale_factor);
%%%% PANEL CT FIGURE - position
pos.PANELax.panel=round([15,15,865,650].*scale_factor);
pos.PANELax.ax=round([145,5,575,575].*scale_factor);
pos.PANELax.SLIDERimage=round([145,580,575,25].*scale_factor);
pos.PANELax.SLIDERcontrast=round([720,5,25,575].*scale_factor);
pos.PANELax.SLIDERwindowUp_edit=round([750,500,80,25].*scale_factor);
pos.PANELax.SLIDERwindowDown_edit=round([750,100,80,25].*scale_factor);
pos.PANELax.SLIDERwindowUp_push=round([750,450,80,25].*scale_factor);
pos.PANELax.SLIDERwindowDown_push=round([750,50,80,25].*scale_factor);
pos.PANELax.ZoomIn=round([760,310,25,25].*scale_factor);
pos.PANELax.ZoomOut=round([760,270,25,25].*scale_factor);
pos.PANELax.TXT=round([145,605,575,25].*scale_factor);
pos.PANELax.colorbar=round([10,5,25,575].*scale_factor);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%% modifica 22/02/2011
pos.PANELroi.panel=round([905,60,235,600].*scale_factor);
pos.PANELroi.popup=round([5,550,225,25].*scale_factor);
pos.PANELroi.PANEL1.panel=round([5,475,225,70].*scale_factor);
pos.PANELroi.PANEL1.PB1=round([55,10,40,40].*scale_factor);
pos.PANELroi.PANEL1.PB2=round([130,10,40,40].*scale_factor);
pos.PANELroi.PANEL2.panel=round([5,360,225,70].*scale_factor);
pos.PANELroi.PANEL2.PB1=round([5,10,40,40].*scale_factor);
pos.PANELroi.PANEL2.PB2=round([60,10,40,40].*scale_factor);
pos.PANELroi.PANEL2.PB3=round([115,10,40,40].*scale_factor);
pos.PANELroi.PANEL2.PB4=round([170,10,40,40].*scale_factor);
pos.PANELroi.PANEL3.panel=round([10,250,225,105].*scale_factor);
pos.PANELroi.PANEL3.TXT1a=round([10,65,120,25].*scale_factor);
pos.PANELroi.PANEL3.PB2=round([10,35,120,25].*scale_factor);
pos.PANELroi.PANEL3.TXT3a=round([10,5,120,25].*scale_factor);
pos.PANELroi.PANEL3.TXT1b=round([130,65,90,25].*scale_factor);
pos.PANELroi.PANEL3.TXT2b=round([130,35,90,25].*scale_factor);
pos.PANELroi.PANEL3.TXT3b=round([130,5,90,25].*scale_factor);
%%%% PANEL 4 CHOICHE OF THE OUTPUT - position
pos.PANELroi.PANEL4.panel=round([5,130,225,115].*scale_factor);
pos.PANELroi.PANEL4.CKBOX1=round([10,65,205,25].*scale_factor);
pos.PANELroi.PANEL4.CKBOX2=round([10,35,205,25].*scale_factor);
pos.PANELroi.PANEL4.CKBOX3=round([10,5,205,25].*scale_factor);
%%%% PANEL 5  SAVE OPTIONS - position
pos.PANELroi.PANEL5.panel=round([5,10,225,115].*scale_factor);
pos.PANELroi.PANEL5.PB1=round([10,65,120,25].*scale_factor);
pos.PANELroi.PANEL5.PB2=round([10,35,120,25].*scale_factor);
pos.PANELroi.PANEL5.PB3=round([10,5,120,25].*scale_factor);
%%%% PANEL waitbar - position
%pos.PANELwaitbar.panel=round([905,60,235,40].*scale_factor);
%%%% PANEL start - position
pos.PBstart=round([905,15,235,40].*scale_factor);

%%%% ausiliarie
pet_gui.prima_apertura=0;
pet_gui.scale4contrast=0.5;

pet_gui.bgc = [0.4 0.4 0.4]; 
pet_gui.bgc_light = [0.4 0.4 0.4];
pet_gui.fgc = [1,1,1]; %[1,0,0];
pet_gui.fs = 16;
pet_gui.bgc_drop = [0.5 0.5 0.5];
pet_gui.fgc_drop = [0.4 0.4 0.4];
pet_gui.bgc_ppm = [0.8 0.8 0.8];
pet_gui.fgc_ppm = [0.4 0.4 0.4];

%% ausiliarie
pet_gui.prima_apertura=0;
%pet_gui.scale4window=200;
pet_gui.scale4contrast=0.5;
%pet_gui.scale4contrast_step=0.1;

%% FIGURE
pet_gui.fig=figure('HandleVisibility','Callback','Menubar','none',...
    'Name','VISUAL CT', 'NumberTitle','off', ...
    'Visible','on', 'BackingStore','off',...
    'position',pos.FIGURE,...
    'Color',pet_gui.bgc);

%% PANEL LOAD
pet_gui.PANELload.panel=uipanel('parent',pet_gui.fig,'Title','Input files','units','pixel',...
    'Position',pos.PANELload.panel,'FontWeight','bold','FontSize',pet_gui.fs,'BackGroundColor',pet_gui.bgc_drop,'ForeGroundColor',pet_gui.fgc);
pet_gui.PANELload.PBload = uicontrol(pet_gui.PANELload.panel,'style', 'pushbutton',...
    'units', 'pixel',...
    'string', 'LOAD',...
    'position',pos.PANELload.PBload,...
    'BackGroundColor',pet_gui.bgc,...
    'ForeGroundColor',pet_gui.fgc,...
    'FontSize',pet_gui.fs,...
    'callback', 'Load_Data');

pet_gui.PANELload.TXTload  = uicontrol(pet_gui.PANELload.panel,'style', 'text',...
    'units', 'pixel',...
    'string', '',...
    'BackGroundColor',pet_gui.bgc_drop,...
    'ForeGroundColor',pet_gui.fgc,...
    'FontSize',pet_gui.fs,...
    'position', pos.PANELload.TXTload);

%% PANEL CT FIGURE
pet_gui.PANELax.panel=uipanel('parent',pet_gui.fig,'Title','CT image','units','pixel',...
    'Position',pos.PANELax.panel,'FontWeight','bold','FontSize',pet_gui.fs,'visible','off',...
    'BackGroundColor',pet_gui.bgc_drop, 'ForeGroundColor',pet_gui.fgc);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
pet_gui.PANELax.SLIDERcontrast=uicontrol(pet_gui.PANELax.panel,'Style','slider','Min',0,'Max',1,...
    'Value',pet_gui.scale4contrast,'SliderStep',[0.01 0.05],...
    'units','pixel',...
    'position',pos.PANELax.SLIDERcontrast,...
    'BackGroundColor',pet_gui.bgc,...
    'ForeGroundColor',pet_gui.fgc,...
    'FontSize',pet_gui.fs,...
    'enable','on',...
    'Callback','Slider_Contrast');
pet_gui.PANELax.SLIDERwindowUp_edit=uicontrol(pet_gui.PANELax.panel,'Style','edit',...
    'string',0,...
    'units','pixel',...
    'visible', 'on',...
    'position',pos.PANELax.SLIDERwindowUp_edit,...
    'BackGroundColor',pet_gui.bgc,...
    'ForeGroundColor',pet_gui.fgc,...
    'FontSize',pet_gui.fs,...
    'enable','on');
pet_gui.PANELax.SLIDERwindowDown_edit=uicontrol(pet_gui.PANELax.panel,'Style','edit',...
    'string',0,...
    'units','pixel',...
    'visible', 'on',...
    'position',pos.PANELax.SLIDERwindowDown_edit,...
    'BackGroundColor',pet_gui.bgc,...
    'ForeGroundColor',pet_gui.fgc,...
    'FontSize',pet_gui.fs,...
    'enable','on');
pet_gui.PANELax.SLIDERwindowUp_push=uicontrol(pet_gui.PANELax.panel,'Style','pushbutton',...
    'String','APPLY',...
    'units','pixel',...
    'position',pos.PANELax.SLIDERwindowUp_push,...
    'BackGroundColor',pet_gui.bgc,...
    'ForeGroundColor',pet_gui.fgc,...
    'FontSize',pet_gui.fs,...
    'enable','on',...
    'callback', 'Slider_WindowUp;');
pet_gui.PANELax.SLIDERwindowDown_push=uicontrol(pet_gui.PANELax.panel,'Style','pushbutton',...
    'String','APPLY',...
    'units','pixel',...
    'position',pos.PANELax.SLIDERwindowDown_push,...
    'BackGroundColor',pet_gui.bgc,...
    'ForeGroundColor',pet_gui.fgc,...
    'FontSize',pet_gui.fs,...
    'enable','on',...
    'callback', 'Slider_WindowDown;');

[X map] = imread(['icon' pet_gui.slash_pc_mac 'zoom_in.gif']);
[X map] = imresize(X,map,1);
icon = ind2rgb(X,map);
pet_gui.PANELax.ZoomIn=uicontrol(pet_gui.PANELax.panel,...
    'units','pixel',...
    'CData', icon,...
    'position',pos.PANELax.ZoomIn,...
    'enable','on',...
    'Callback', 'zoom on',...
    'CData',icon,...
    'TooltipString','Zoom',...
    'Tag','zoom');
[X map] = imread(['icon' pet_gui.slash_pc_mac 'zoom_out.gif']);
[X map] = imresize(X,map,1);
icon = ind2rgb(X,map);
pet_gui.PANELax.ZoomOut=uicontrol(pet_gui.PANELax.panel,...
    'units','pixel',...
    'CData', icon,...
    'position',pos.PANELax.ZoomOut,...
    'enable','on',...
    'Callback', 'zoom off',...
    'CData',icon,...
    'TooltipString','Zoom',...
    'Tag','zoom');
pet_gui.PANELax.SLIDERimage=uicontrol(pet_gui.PANELax.panel,'Style','slider','Min',0,'Max',1,...
    'Value',0,...
    'units','pixel',...
    'position',pos.PANELax.SLIDERimage,...
    'BackGroundColor',pet_gui.bgc,...
    'ForeGroundColor',pet_gui.fgc,...
    'FontSize',pet_gui.fs,...
    'enable','on',...
    'Callback','Slider_Image');
pet_gui.PANELax.TXT= uicontrol(pet_gui.PANELax.panel,'style', 'text',...
    'units', 'pixel',...
    'string','',...
    'BackGroundColor',pet_gui.bgc_drop,...
    'ForeGroundColor',pet_gui.fgc,...
    'FontSize',pet_gui.fs,...
    'position', pos.PANELax.TXT);
pet_gui.PANELax.ax=axes('parent',pet_gui.PANELax.panel,...
    'units','pixel',...
    'Position',pos.PANELax.ax,...
    'xlim',[0.5 512.5],'ylim',[0.5 512.5]);

%% PANEL ROI
pet_gui.PANELroi.ROIName={...
    '--------------------',...
    'Total Body          ',...
    'Vertebrae C1-C7     ',...
    'Vertebrae T1-T12    ',...
    'Vertebrae L1-L5     ',...
    'Vertebrae S1-S5     ',...
    'Sternum             ',...
    'Epiphysis Humerus R ',...
    'Epiphysis Humerus L ',...
    'Diaphysis Humerus R ',...
    'Diaphysis Humerus L ',...
    'Iliac Crest R       ',...
    'Iliac Crest L       ',...
    'Epiphysis Femur R   ',...
    'Epiphysis Femur L   ',...
    'Diaphysis Femur R   ',...
    'Diaphysis Femur L   ',...
    'Whole leg R         ',...
    'Whole leg L         ',...
    'Total body w/o spine'};%,...
%'New ROI..........'};
pet_gui.PANELroi.ROIId=[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,-1];

pet_gui.PANELroi.panel=uipanel('parent',pet_gui.fig,'Title','ROI','units','pixel',...
    'Position',pos.PANELroi.panel,'FontWeight','bold','FontSize',pet_gui.fs,'BackGroundColor',pet_gui.bgc_drop,'ForeGroundColor',pet_gui.fgc);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
pet_gui.PANELroi.popup=uicontrol(pet_gui.PANELroi.panel,'style', 'popup',...
    'string',pet_gui.PANELroi.ROIName,...
    'units','pixel',...
    'callback','PopUp_Districts',...
    'enable','off',...
    'BackGroundColor',pet_gui.bgc_ppm,...
    'ForeGroundColor',pet_gui.fgc_ppm, ...
    'FontSize',pet_gui.fs,...
    'FontWeight','bold',...
    'position',pos.PANELroi.popup);

%%%%%%%%%%%%%%%%%%%%%%%%      PANEL 2 choice of the roi kind      %%%%%%%%%%%%%%%%%%%%%%%%%%%
pet_gui.PANELroi.PANEL2.panel=uipanel('parent',pet_gui.PANELroi.panel,...
    'Title','ROI kind',...
    'units','pixel',...
    'Position',pos.PANELroi.PANEL2.panel,'FontWeight','bold','FontSize',pet_gui.fs,'BackGroundColor',pet_gui.bgc,'ForeGroundColor',pet_gui.fgc);

[X map] = imread(['icon' pet_gui.slash_pc_mac 'rectangle.ico']);
[X map] = imresize(X,map,0.5);
icon = ind2rgb(X,map);
pet_gui.PANELroi.PANEL2.PB1 = uicontrol(pet_gui.PANELroi.PANEL2.panel,'style', 'pushbutton',...
    'units', 'pixel',...
    'CData', icon,...
    'position',pos.PANELroi.PANEL2.PB1,...
    'enable','off',...
    'callback', 'Roi_Rectangle;');
[X map] = imread(['icon' pet_gui.slash_pc_mac 'ellipse.ico']);
[X map] = imresize(X,map,0.5);
icon = ind2rgb(X,map);
pet_gui.PANELroi.PANEL2.PB2 = uicontrol(pet_gui.PANELroi.PANEL2.panel,'style', 'pushbutton',...
    'units', 'pixel',...
    'CData', icon,...
    'position',pos.PANELroi.PANEL2.PB2,...
    'enable','off',...
    'callback', 'Roi_Ellipse;');
[X map] = imread(['icon' pet_gui.slash_pc_mac 'poly.ico']);
[X map] = imresize(X,map,0.5);
icon = ind2rgb(X,map);
pet_gui.PANELroi.PANEL2.PB3 = uicontrol(pet_gui.PANELroi.PANEL2.panel,'style', 'pushbutton',...
    'units', 'pixel',...
    'CData', icon,...
    'position',pos.PANELroi.PANEL2.PB3,...
    'enable','off',...
    'callback', 'Roi_Poly;');
[X map] = imread(['icon' pet_gui.slash_pc_mac 'sphere.ico']);
[X map] = imresize(X,map,0.5);
icon = ind2rgb(X,map);
pet_gui.PANELroi.PANEL2.PB4 = uicontrol(pet_gui.PANELroi.PANEL2.panel,'style', 'pushbutton',...
    'units', 'pixel',...
    'CData', icon,...
    'position',pos.PANELroi.PANEL2.PB4,...
    'enable','off',...
    'callback', 'Roi_Sphere;');
%%%%%%%%%%%%%%%%%%%%%%%%      PANEL 3  end of the roi     %%%%%%%%%%%%%%%%%%%%%%%%%%%
pet_gui.PANELroi.PANEL3.panel=uipanel('parent',pet_gui.PANELroi.panel,...
    'Title','',...
    'units','pixel',...
    'Position',pos.PANELroi.PANEL3.panel,'FontWeight','bold','BackGroundColor',pet_gui.bgc,'ForeGroundColor',pet_gui.fgc);
pet_gui.PANELroi.PANEL3.TXT1a = uicontrol(pet_gui.PANELroi.PANEL3.panel,'style', 'text',...
    'units', 'pixel',...
    'string', 'START',...
    'BackGroundColor',pet_gui.bgc,...
    'ForeGroundColor',pet_gui.fgc,...
    'FontSize',pet_gui.fs,...
    'position',pos.PANELroi.PANEL3.TXT1a,...
    'enable','off');%,...
%'callback', ' ;');
pet_gui.PANELroi.PANEL3.PB2 = uicontrol(pet_gui.PANELroi.PANEL3.panel,'style', 'pushbutton',...
    'units', 'pixel',...
    'string', 'END',...
    'BackGroundColor',pet_gui.bgc,...
    'ForeGroundColor',pet_gui.fgc,...
    'FontSize',pet_gui.fs,...
    'position',pos.PANELroi.PANEL3.PB2,...
    'enable','off',...
    'callback', 'Roi_End;');
pet_gui.PANELroi.PANEL3.TXT3a = uicontrol(pet_gui.PANELroi.PANEL3.panel,'style', 'text',...
    'units', 'pixel',...
    'string', 'CENTER',...
    'BackGroundColor',pet_gui.bgc,...
    'ForeGroundColor',pet_gui.fgc,...
    'FontSize',pet_gui.fs,...
    'enable','off',...
    'position',pos.PANELroi.PANEL3.TXT3a);%,...
%'callback', ' ;');
pet_gui.PANELroi.PANEL3.TXT1b= uicontrol(pet_gui.PANELroi.PANEL3.panel,'style', 'text',...
    'units', 'pixel',...
    'string', '',...
    'BackGroundColor',pet_gui.bgc,...
    'ForeGroundColor',pet_gui.fgc,...
    'FontSize',pet_gui.fs,...
    'position', pos.PANELroi.PANEL3.TXT1b);
pet_gui.PANELroi.PANEL3.TXT2b= uicontrol(pet_gui.PANELroi.PANEL3.panel,'style', 'text',...
    'units', 'pixel',...
    'string', '',...
    'BackGroundColor',pet_gui.bgc,...
    'ForeGroundColor',pet_gui.fgc,...
    'FontSize',pet_gui.fs,...
    'position', pos.PANELroi.PANEL3.TXT2b);
pet_gui.PANELroi.PANEL3.TXT3b= uicontrol(pet_gui.PANELroi.PANEL3.panel,'style', 'text',...
    'units', 'pixel',...
    'string', '',...
    'BackGroundColor',pet_gui.bgc,...
    'ForeGroundColor',pet_gui.fgc,...
    'FontSize',pet_gui.fs,...
    'position', pos.PANELroi.PANEL3.TXT3b);
%%%%%%%%%%%%%%%%%%%%%%%%      PANEL 4   choice of the output    %%%%%%%%%%%%%%%%%%%%%%%%%%%
pet_gui.PANELroi.PANEL4.panel=uipanel('parent',pet_gui.PANELroi.panel,...
    'Title','Output',...
    'units','pixel',...
    'Position',pos.PANELroi.PANEL4.panel,'FontWeight','bold','FontSize',pet_gui.fs,'BackGroundColor',pet_gui.bgc,'ForeGroundColor',pet_gui.fgc);

pet_gui.PANELroi.PANEL4.CKBOX1 = uicontrol(pet_gui.PANELroi.PANEL4.panel,'style', 'checkbox',...
    'units', 'pixel',...
    'string', 'ENABLE ROI',...
    'BackGroundColor',pet_gui.bgc,...
    'ForeGroundColor',pet_gui.fgc,...
    'FontSize',pet_gui.fs,...
    'enable','on',...
    'callback','Enable_Roi',...
    'position',pos.PANELroi.PANEL4.CKBOX1);
pet_gui.PANELroi.PANEL4.CKBOX2 = uicontrol(pet_gui.PANELroi.PANEL4.panel,'style', 'checkbox',...
    'units', 'pixel',...
    'string', 'TXT',...
    'BackGroundColor',pet_gui.bgc,...
    'ForeGroundColor',pet_gui.fgc,...
    'FontSize',pet_gui.fs,...
    'enable','on',...
    'callback','Enable_Txt',...
    'position',pos.PANELroi.PANEL4.CKBOX2);
pet_gui.PANELroi.PANEL4.CKBOX3 = uicontrol(pet_gui.PANELroi.PANEL4.panel,'style', 'checkbox',...
    'units', 'pixel',...
    'string', 'DICOM',...
    'BackGroundColor',pet_gui.bgc,...
    'ForeGroundColor',pet_gui.fgc,...
    'FontSize',pet_gui.fs,...
    'enable','on',...
    'callback','Enable_Dicom',...
    'position',pos.PANELroi.PANEL4.CKBOX3);

%%%%%%%%%%%%%%%%%%%%%%%%      PANEL 5  ROI save options     %%%%%%%%%%%%%%%%%%%%%%%%%%%
pet_gui.PANELroi.PANEL5.panel=uipanel('parent',pet_gui.PANELroi.panel,...
    'Title','Save',...
    'units','pixel',...
    'Position',pos.PANELroi.PANEL5.panel,'FontWeight','bold','FontSize',pet_gui.fs,'BackGroundColor',pet_gui.bgc,'ForeGroundColor',pet_gui.fgc);

pet_gui.PANELroi.PANEL5.PB1 = uicontrol(pet_gui.PANELroi.PANEL5.panel,'style', 'pushbutton',...
    'units', 'pixel',...
    'string', 'RESET ROI',...
    'BackGroundColor',pet_gui.bgc,...
    'ForeGroundColor',pet_gui.fgc,...
    'FontSize',pet_gui.fs,...
    'enable','off',...
    'position',pos.PANELroi.PANEL5.PB1,...
    'callback', 'Reset_Roi;');
pet_gui.PANELroi.PANEL5.PB2 = uicontrol(pet_gui.PANELroi.PANEL5.panel,'style', 'pushbutton',...
    'units', 'pixel',...
    'string', 'RESET ALL',...
    'BackGroundColor',pet_gui.bgc,...
    'ForeGroundColor',pet_gui.fgc,...
    'FontSize',pet_gui.fs,...
    'enable','off',...
    'position',pos.PANELroi.PANEL5.PB2,...
    'callback', 'Reset_All;');
pet_gui.PANELroi.PANEL5.PB3 = uicontrol(pet_gui.PANELroi.PANEL5.panel,'style', 'pushbutton',...
    'units', 'pixel',...
    'string', 'SAVE ALL',...
    'BackGroundColor',pet_gui.bgc,...
    'ForeGroundColor',pet_gui.fgc,...
    'FontSize',pet_gui.fs,...
    'enable','off',...
    'position',pos.PANELroi.PANEL5.PB3,...
    'callback', 'Save_All;');
%% WAITBAR
%%%%%%%%%%%%%%%%%%%%%%%%%%%%% modifica 22/02/2011
%pet_gui.PANELwaitbar.panel=uipanel('parent',pet_gui.fig,'units','pixel',...
%    'Position',pos.PANELwaitbar.panel);
%pet_gui.PANELwaitbar.waitbar=waitbar2a(0,pet_gui.PANELwaitbar.panel);
%waitbar2a(0, pet_gui.PANELwaitbar.waitbar,' ');
%%%%%%%%%%%%%%%%%%%%%%%%%%%%% end modifica 22/02/2011
%% START ANALYSIS

pet_gui.PBstart = uicontrol('parent',pet_gui.fig,'style', 'pushbutton',...
    'units', 'pixel',...
    'string', 'START ANALYSIS',...
    'BackGroundColor',pet_gui.bgc_drop,...
    'ForeGroundColor',pet_gui.fgc,...
    'FontSize',pet_gui.fs,...
    'enable','off',...
    'position',pos.PBstart,...
    'callback', 'Start_Analysis');

pet_gui.PopupValue=0;


pet_gui.MENU.View.Menu=uimenu(pet_gui.fig,'label','&View');

pet_gui.MENU.View.SliceSelect=uimenu(pet_gui.MENU.View.Menu,'Label','&Select slice',...
    'Accelerator','W','Callback','main_gui(''MenuCallback_SliceSelect'')',...
    'enable','off');
pet_gui.MENU.View.SlicePlus=uimenu(pet_gui.MENU.View.Menu,'Label','&Zoom +',...
    'Accelerator','D','Callback','main_gui(''MenuCallback_ZoomIn'')',...
    'enable','off');
pet_gui.MENU.View.SliceMinus=uimenu(pet_gui.MENU.View.Menu,'Label','&Zoom -',...
    'Accelerator','A','Callback','main_gui(''MenuCallback_ZoomOut'')',...
    'enable','off');
%%%%%%%%%%%%%%%%%%
pet_gui.MENU.View.HURange=uimenu(pet_gui.MENU.View.Menu,'Label','&HU range',...
    'Callback','main_gui(''MenuCallback_HURange'')',...
    'enable','off');
end

function MenuCallback_SliceSelect()
global pet_gui;
global Info;

answer=inputdlg('Set Slice Number:','Slice Number',1);

if ~isempty(answer)
    SliceNumber=str2num(answer{1});    
    if ~isempty(SliceNumber)
        if SliceNumber>=1 && SliceNumber<=Info.NumberFileCT(pet_gui.SelectedCT)
            set(pet_gui.PANELax.SLIDERimage, 'Value',(SliceNumber-1)/(Info.NumberFileCT(pet_gui.SelectedCT)-1));
            Callback_SliderImage();
        end
    end
end


end

function MenuCallback_ZoomIn()
global pet_gui;

axs = pet_gui.PANELax.ax;
scrolls = 1;
% get the axes' x- and y-limits
xlim = get(axs, 'xlim');  ylim = get(axs, 'ylim');

xlim_new=[xlim(1)+scrolls*5 , xlim(2)-scrolls*5];
ylim_new=[ylim(1)+scrolls*5 , ylim(2)-scrolls*5];
if xlim_new(2) - xlim_new(1) <= 1, return, end
if ylim_new(2) - ylim_new(1) <= 1, return, end
if xlim_new(2) - xlim_new(1) > 512, return, end
if ylim_new(2) - ylim_new(1) > 512, return, end

set(axs, 'xlim', xlim_new, 'ylim',ylim_new);
end

function MenuCallback_ZoomOut()
global pet_gui;

axs = pet_gui.PANELax.ax;
scrolls = -1;
% get the axes' x- and y-limits
xlim = get(axs, 'xlim');  ylim = get(axs, 'ylim');

xlim_new=[xlim(1)+scrolls*5 , xlim(2)-scrolls*5];
ylim_new=[ylim(1)+scrolls*5 , ylim(2)-scrolls*5];
if xlim_new(2) - xlim_new(1) <= 1, return, end
if ylim_new(2) - ylim_new(1) <= 1, return, end
if xlim_new(2) - xlim_new(1) > 512, return, end
if ylim_new(2) - ylim_new(1) > 512, return, end

set(axs, 'xlim', xlim_new, 'ylim',ylim_new);
end

function MenuCallback_HURange()
global pet_gui;
global Info;

prompt = {'From:','To:'};
dlg_title = 'HU Range';
num_lines = 1;
def = {'-110','190'};
answer = inputdlg(prompt,dlg_title,num_lines,def);

if ~isempty(answer)
    if ~isempty(answer{1}) && ~isempty(answer{2})
        CLim_min=str2num(answer{1})+1024;
        CLim_max=str2num(answer{2})+1024;
        if ~isempty(CLim_min) || ~isempty(CLim_max)
            if CLim_min<CLim_max
                set(pet_gui.PANELax.ax, 'CLim', [CLim_min CLim_max]);

                set(pet_gui.PANELax.colorbar,'xtick',[ceil(CLim_min),floor(CLim_max)]);

                set(pet_gui.PANELax.colorbar,'xticklabel',{num2str(ceil(CLim_min-1024)),num2str(ceil(CLim_max-1024))});
            end
            
        end
    end

end
end